version: '3.8'

services:
  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: "!@#$%^&*()"
      MYSQL_DATABASE: mosbank
      MYSQL_USER: spring
      MYSQL_PASSWORD: spring
    volumes:
      - ./mysqlScriptForDocker.sql:/docker-entrypoint-initdb.d/mysqlScriptForDocker.sql
    command: --init-file /docker-entrypoint-initdb.d/grant_privileges.sql
    ports:
      - "3306:3306"

  app:
    build:
      context: .
      dockerfile: DockerfileJava
    depends_on:
      - db
    ports:
      - "8080:8080"
